### ISSUE TITLE
Make BootInfo repr(C)

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/os_bootinfo#1]
The bootinfo is passed between different executables (the bootloader and the kernel), which might have been compiled with different rustc versions. The Rust ABI is not stable, so things could break.

To fix this, we should make BootInfo `repr(C)`, so that is has a defined ABI. (This means that we perhaps need to write our own `repr(C)` version of ArrayVec.)

**Comment by lachlansneff** [comment]
Using an external crate does seem a little overkill if all the MemoryMap type needs to do is act as a simple queue.

**Comment by phil-opp** [comment]
Sure, it was just convenient for prototyping (e.g. ArrayVec already implements a lot of useful methods and traits). But I agree that implementing our own queue wouldn't be hard either.

**Comment by phil-opp** [comment]
Was already fixed somewhere on the way.
